/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUIKit/ControlCenterUIKit-Structs.h>
#import <UIKit/UILabel.h>

@interface CCUIControlCenterLabel : UILabel {

	NSUInteger _style;

}

@property (assign,nonatomic) NSUInteger style;			//@synthesize style=_style - In the implementation block
- (id)initWithFrame:(CGRect)arg1;
- (NSUInteger)style;
- (void)setHighlighted:(BOOL)arg1;
- (void)setEnabled:(BOOL)arg1;
- (void)setStyle:(NSUInteger)arg1;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)_updateEffects;
@end
