/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUIKit/ControlCenterUIKit-Structs.h>
#import <ControlCenterUIKit/CCUIMenuModuleItem.h>
#import <UIKit/UIControl.h>

@class UILabel, UIImage, UIView, UIImageView;

@interface CCUIMenuModuleItemView : UIControl {

	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	UIImage* _glyphImage;
	UIView* _separatorView;
	UIImageView* _glyphImageView;
	UIView* _highlightedBackgroundView;
	BOOL _separatorVisible;
	BOOL _useTallLayout;
	/*^block*/ id _handler;
	CGFloat _preferredMaxLayoutWidth;
   CCUIMenuModuleItemView* _menuItem;
   UIView* _leadingView;
   UIView* _trailingView;

}

@property (nonatomic) UIView *leadingView;
@property (nonatomic) UIView *trailingView;
@property (nonatomic) CCUIMenuModuleItemView *menuItem;
@property (nonatomic,copy,readonly) id handler;					//@synthesize handler=_handler - In the implementation block
@property (assign,nonatomic) BOOL separatorVisible;				//@synthesize separatorVisible=_separatorVisible - In the implementation block
@property (assign,nonatomic) CGFloat preferredMaxLayoutWidth;			//@synthesize preferredMaxLayoutWidth=_preferredMaxLayoutWidth - In the implementation block
@property (assign,nonatomic) BOOL useTallLayout;				//@synthesize useTallLayout=_useTallLayout - In the implementation block
- (void)layoutSubviews;
- (CGSize)sizeThatFits:(CGSize)arg1;
- (CGSize)intrinsicContentSize;
- (void)setHighlighted:(BOOL)arg1;
- (void)setEnabled:(BOOL)arg1;
- (void)_setContinuousCornerRadius:(CGFloat)arg1;
- (void)setSelected:(BOOL)arg1;
- (void)setPreferredMaxLayoutWidth:(CGFloat)arg1;
- (CGFloat)preferredMaxLayoutWidth;
- (id)handler;
- (void)_updateForStateChange;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 glyphImage:(id)arg3 handler:(/*^block*/ id)arg4;
- (void)setUseTallLayout:(BOOL)arg1;
- (BOOL)useTallLayout;
- (CGFloat)_titleBaselineToTop;
- (CGFloat)_titleBaselineToBottom;
- (BOOL)_shouldCenterText;
- (CGFloat)_glyphMargin;
- (BOOL)separatorVisible;
- (id)initWithTitle:(id)arg1 glyphImage:(id)arg2 handler:(/*^block*/ id)arg3;
- (void)setSeparatorVisible:(BOOL)arg1;
- (UIEdgeInsets)_labelInsets;
@end
