/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUIKit/ControlCenterUIKit-Structs.h>
#import "SBFButton.h"
#import "_UISettingsKeyObserver.h"

@protocol CCUIControlCenterButtonDelegate;
@class UIColor, UIImageView, UILabel, UIView, UIImage, UIFont, NSString;

@interface CCUIControlCenterButton : SBFButton <_UISettingsKeyObserver> {

	NSUInteger _buttonType;
	UIColor* _selectedColor;
	UIImageView* _glyphImageView;
	UILabel* _label;
	UIImageView* _alteredStateGlyphImageView;
	UILabel* _alteredStateLabel;
	UIView* _backgroundFlatColorView;
	BOOL _animatesStateChanges;
	BOOL _showingMenu;
	id<CCUIControlCenterButtonDelegate> _delegate;
	NSUInteger _roundCorners;
	UIImage* _glyphImage;
	UIImage* _selectedGlyphImage;
	CGFloat _naturalHeight;

}

@property (nonatomic,retain) UIImage * glyphImage;                                             //@synthesize glyphImage=_glyphImage - In the implementation block
@property (nonatomic,retain) UIImage * selectedGlyphImage;                                     //@synthesize selectedGlyphImage=_selectedGlyphImage - In the implementation block
@property (assign,nonatomic) CGFloat naturalHeight;                                             //@synthesize naturalHeight=_naturalHeight - In the implementation block
@property (nonatomic,weak) id<CCUIControlCenterButtonDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) BOOL animatesStateChanges;                                        //@synthesize animatesStateChanges=_animatesStateChanges - In the implementation block
@property (getter=isInternal,nonatomic,readonly) BOOL internal;
@property (assign,nonatomic) NSUInteger roundCorners;                                  //@synthesize roundCorners=_roundCorners - In the implementation block
@property (assign,getter=isShowingMenu,nonatomic) BOOL showingMenu;                            //@synthesize showingMenu=_showingMenu - In the implementation block
@property (nonatomic,retain) UIFont * font;
@property (assign,nonatomic) NSInteger numberOfLines;
@property (nonatomic,retain) NSString * text;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
+(id)_buttonWithSelectedColor:(id)arg1 text:(id)arg2 type:(NSUInteger)arg3 ;
+(id)smallCircularButtonWithSelectedColor:(id)arg1 ;
+(id)circularButtonWithSelectedColor:(id)arg1 ;
+(id)roundRectButton;
+(id)roundRectButtonWithText:(id)arg1 ;
+(id)roundRectButtonWithText:(id)arg1 selectedGlyphColor:(id)arg2 ;
+(id)capsuleButtonWithText:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setFrame:(CGRect)arg1 ;
-(void)setNumberOfLines:(NSInteger)arg1 ;
-(CGFloat)cornerRadius;
-(void)layoutSubviews;
-(id<CCUIControlCenterButtonDelegate>)delegate;
-(void)setDelegate:(id<CCUIControlCenterButtonDelegate>)arg1 ;
-(void)dealloc;
-(void)setBounds:(CGRect)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(CGSize)intrinsicContentSize;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
-(void)setFont:(UIFont *)arg1 ;
-(void)setBackgroundImage:(id)arg1 forState:(NSUInteger)arg2 ;
-(void)setEnabled:(BOOL)arg1 ;
-(void)_setButtonType:(NSUInteger)arg1 ;
-(BOOL)_shouldAnimatePropertyWithKey:(id)arg1 ;
-(void)didMoveToSuperview;
-(UIFont *)font;
-(NSInteger)numberOfLines;
-(void)settings:(id)arg1 changedValueForKey:(id)arg2 ;
-(void)setImage:(id)arg1 forState:(NSUInteger)arg2 ;
-(void)_updateEffects;
-(UIImage *)glyphImage;
-(void)setGlyphImage:(UIImage *)arg1 ;
-(void)setSelectedGlyphImage:(UIImage *)arg1 ;
-(UIImage *)selectedGlyphImage;
-(BOOL)_drawingAsSelected;
-(CGFloat)naturalHeight;
-(void)_updateForStateChange;
-(NSInteger)_currentState;
-(void)setShowingMenu:(BOOL)arg1 ;
-(BOOL)isShowingMenu;
-(id)initWithFrame:(CGRect)arg1 selectedColor:(id)arg2 text:(id)arg3 type:(NSUInteger)arg4 ;
-(BOOL)_isCircleButton;
-(BOOL)_isRectButton;
-(BOOL)_isCapsuleButton;
-(BOOL)_isTextButton;
-(void)_updateBackgroundForStateChange;
-(void)_pressAction;
-(void)_updateForReduceTransparencyChange;
-(void)_updateForDarkerSystemColorsChange:(id)arg1 ;
-(void)_calculateRectForGlyph:(CGRect*)arg1 rectForLabel:(CGRect*)arg2 ignoringBounds:(BOOL)arg3 ;
-(id)_glyphImageForState:(NSInteger)arg1 ;
-(void)_updateNaturalHeight;
-(void)_updateGlyphAndTextForStateChange;
-(void)setNaturalHeight:(CGFloat)arg1 ;
-(id)_effectiveSelectedColor;
-(NSUInteger)roundCorners;
-(BOOL)animatesStateChanges;
-(id)_controlStateStringFromState:(NSInteger)arg1 ;
-(BOOL)_isRectTextButton;
-(void)setRoundCorners:(NSUInteger)arg1 ;
-(void)setAnimatesStateChanges:(BOOL)arg1 ;
-(id)ccuiPunchOutMaskForView:(id)arg1 ;
-(void)setGlyphImage:(id)arg1 selectedGlyphImage:(id)arg2 name:(id)arg3 ;
-(BOOL)isInternal;
@end
