/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUIKit/ControlCenterUIKit-Structs.h>
#import <UIKit/UIView.h>

@class NSString, UIImage, CCUICAPackageDescription, CCUIRoundButton, UIColor, UILabel;

@interface CCUILabeledRoundButton : UIView {

	BOOL _labelsVisible;
	NSString* _title;
	NSString* _subtitle;
	UIImage* _glyphImage;
	CCUICAPackageDescription* _glyphPackageDescription;
	NSString* _glyphState;
	CCUIRoundButton* _buttonView;
	UIColor* _highlightColor;
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;

}

@property (nonatomic,retain) UIColor * highlightColor;						//@synthesize highlightColor=_highlightColor - In the implementation block
@property (nonatomic,retain) CCUIRoundButton * buttonView;					//@synthesize buttonView=_buttonView - In the implementation block
@property (nonatomic,retain) UILabel * titleLabel;						//@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,retain) UILabel * subtitleLabel;						//@synthesize subtitleLabel=_subtitleLabel - In the implementation block
@property (nonatomic,retain) UIImage * glyphImage;						//@synthesize glyphImage=_glyphImage - In the implementation block
@property (nonatomic,retain) CCUICAPackageDescription * glyphPackageDescription;		//@synthesize glyphPackageDescription=_glyphPackageDescription - In the implementation block
@property (nonatomic,copy) NSString * glyphState;						//@synthesize glyphState=_glyphState - In the implementation block
@property (nonatomic,copy) NSString * title;							//@synthesize title=_title - In the implementation block
@property (nonatomic,copy) NSString * subtitle;							//@synthesize subtitle=_subtitle - In the implementation block
@property (assign,nonatomic) BOOL labelsVisible;						//@synthesize labelsVisible=_labelsVisible - In the implementation block
- (void)layoutSubviews;
- (void)dealloc;
- (void)setTitle:(NSString *)arg1;
- (CGSize)sizeThatFits:(CGSize)arg1;
- (CGSize)intrinsicContentSize;
- (NSString *)title;
- (UILabel *)titleLabel;
- (void)setSubtitle:(NSString *)arg1;
- (NSString *)subtitle;
- (UIColor *)highlightColor;
- (void)setHighlightColor:(UIColor *)arg1;
- (void)setTitleLabel:(UILabel *)arg1;
- (void)_layoutLabels;
- (void)buttonTapped:(id)arg1;
- (void)setButtonView:(CCUIRoundButton *)arg1;
- (UIImage *)glyphImage;
- (void)setGlyphImage:(UIImage *)arg1;
- (void)_contentSizeCategoryDidChange;
- (UILabel *)subtitleLabel;
- (void)setSubtitleLabel:(UILabel *)arg1;
- (id)initWithGlyphImage:(id)arg1 highlightColor:(id)arg2 useLightStyle:(BOOL)arg3;
- (id)initWithGlyphPackageDescription:(id)arg1 highlightColor:(id)arg2 useLightStyle:(BOOL)arg3;
- (void)setGlyphPackageDescription:(CCUICAPackageDescription *)arg1;
- (void)setGlyphState:(NSString *)arg1;
- (void)setLabelsVisible:(BOOL)arg1;
- (id)initWithGlyphImage:(id)arg1 highlightColor:(id)arg2;
- (id)initWithGlyphPackageDescription:(id)arg1 highlightColor:(id)arg2;
- (CCUICAPackageDescription *)glyphPackageDescription;
- (NSString *)glyphState;
- (BOOL)labelsVisible;
- (id)initWithHighlightColor:(id)arg1 useLightStyle:(BOOL)arg2;
- (void)_setupLabelsBounds;
- (BOOL)_shouldUseLargeTextLayout;
- (CCUIRoundButton *)buttonView;
@end
