/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

@class CALayer;


@protocol CCUIGroupRendering <NSObject>
@property (getter=isGroupRenderingRequired,nonatomic,readonly) BOOL groupRenderingRequired;
@property (nonatomic,readonly) CALayer * punchOutRootLayer;
@required
- (BOOL)isGroupRenderingRequired;
- (CALayer *)punchOutRootLayer;

@end
