/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUIKit/ControlCenterUIKit-Structs.h>
#import <UIKit/UIControl.h>

@class CCUICAPackageDescription, UIImage, NSString, UIColor, UIView, UIImageView, CCUICAPackageView;

@interface CCUIRoundButton : UIControl <UIGestureRecognizerDelegate> {

	CCUICAPackageDescription* _glyphPackageDescription;
	UIImage* _glyphImage;
	NSString* _glyphState;
	UIColor* _highlightColor;
	UIView* _normalStateBackgroundView;
	UIView* _selectedStateBackgroundView;
	UIImageView* _glyphImageView;
	UIImageView* _selectedGlyphView;
	CCUICAPackageView* _glyphPackageView;

}

@property (nonatomic,retain) UIColor * highlightColor;						//@synthesize highlightColor=_highlightColor - In the implementation block
@property (nonatomic,retain) UIView * normalStateBackgroundView;				//@synthesize normalStateBackgroundView=_normalStateBackgroundView - In the implementation block
@property (nonatomic,retain) UIView * selectedStateBackgroundView;				//@synthesize selectedStateBackgroundView=_selectedStateBackgroundView - In the implementation block
@property (nonatomic,retain) UIImageView * glyphImageView;					//@synthesize glyphImageView=_glyphImageView - In the implementation block
@property (nonatomic,retain) UIImageView * selectedGlyphView;					//@synthesize selectedGlyphView=_selectedGlyphView - In the implementation block
@property (nonatomic,retain) CCUICAPackageView * glyphPackageView;				//@synthesize glyphPackageView=_glyphPackageView - In the implementation block
@property (nonatomic,retain) CCUICAPackageDescription * glyphPackageDescription;		//@synthesize glyphPackageDescription=_glyphPackageDescription - In the implementation block
@property (nonatomic,retain) UIImage * glyphImage;						//@synthesize glyphImage=_glyphImage - In the implementation block
@property (nonatomic,copy) NSString * glyphState;						//@synthesize glyphState=_glyphState - In the implementation block
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
- (void)layoutSubviews;
- (void)dealloc;
- (CGSize)sizeThatFits:(CGSize)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (CGSize)intrinsicContentSize;
- (CGFloat)_cornerRadius;
- (void)_setCornerRadius:(CGFloat)arg1;
- (void)_handlePressGesture:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (UIColor *)highlightColor;
- (void)setHighlightColor:(UIColor *)arg1;
- (UIImage *)glyphImage;
- (void)setGlyphImage:(UIImage *)arg1;
- (void)_updateForStateChange;
- (void)setGlyphImageView:(UIImageView *)arg1;
- (UIImageView *)glyphImageView;
- (id)initWithGlyphImage:(id)arg1 highlightColor:(id)arg2 useLightStyle:(BOOL)arg3;
- (id)initWithGlyphPackageDescription:(id)arg1 highlightColor:(id)arg2 useLightStyle:(BOOL)arg3;
- (void)setGlyphPackageDescription:(CCUICAPackageDescription *)arg1;
- (void)setGlyphState:(NSString *)arg1;
- (id)initWithGlyphImage:(id)arg1 highlightColor:(id)arg2;
- (id)initWithGlyphPackageDescription:(id)arg1 highlightColor:(id)arg2;
- (CCUICAPackageDescription *)glyphPackageDescription;
- (NSString *)glyphState;
- (void)_primaryActionPerformed:(id)arg1;
- (id)initWithHighlightColor:(id)arg1 useLightStyle:(BOOL)arg2;
- (UIView *)normalStateBackgroundView;
- (void)setNormalStateBackgroundView:(UIView *)arg1;
- (UIView *)selectedStateBackgroundView;
- (void)setSelectedStateBackgroundView:(UIView *)arg1;
- (UIImageView *)selectedGlyphView;
- (void)setSelectedGlyphView:(UIImageView *)arg1;
- (CCUICAPackageView *)glyphPackageView;
- (void)setGlyphPackageView:(CCUICAPackageView *)arg1;
@end
