/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import "CCUIContentModule.h"
#import "CCUIContentModuleContentViewController.h"

@class UIViewController, CCUIToggleViewController, CCUIContentModuleContext, CCUICAPackageDescription, UIImage, UIColor, NSString;

@interface CCUIToggleModule : NSObject <CCUIContentModule> {

	CCUIToggleViewController* _viewController;
	CCUIContentModuleContext* _contentModuleContext;
	CCUICAPackageDescription* _glyphPackageDescription;

}

@property (nonatomic,retain) CCUIContentModuleContext * contentModuleContext;							//@synthesize contentModuleContext=_contentModuleContext - In the implementation block
@property (assign,getter=isSelected,nonatomic) BOOL selected;
@property (nonatomic,copy,readonly) UIImage * iconGlyph;
@property (nonatomic,copy,readonly) UIImage * selectedIconGlyph;
@property (nonatomic,copy,readonly) UIColor * selectedColor;
@property (nonatomic,copy,readonly) CCUICAPackageDescription * glyphPackageDescription;						//@synthesize glyphPackageDescription=_glyphPackageDescription - In the implementation block
@property (nonatomic,copy,readonly) NSString * glyphState;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
@property (nonatomic,readonly) UIViewController<CCUIContentModuleContentViewController>* contentViewController;
@property (nonatomic,readonly) UIViewController * backgroundViewController;
- (BOOL)isSelected;
- (void)setSelected:(BOOL)arg1;
- (UIViewController<CCUIContentModuleContentViewController>*)contentViewController;
- (CCUICAPackageDescription *)glyphPackageDescription;
- (NSString *)glyphState;
- (void)reconfigureView;
- (UIImage *)iconGlyph;
- (UIImage *)selectedIconGlyph;
- (id)glyphPackage;
- (CCUIContentModuleContext *)contentModuleContext;
- (void)setContentModuleContext:(CCUIContentModuleContext *)arg1;
- (void)refreshState;
- (UIColor *)selectedColor;
@end
