/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import "CCUIContentModuleContentViewController.h"

@protocol CCUIContentModuleContentViewController <NSObject>
@property (nonatomic,readonly) CGFloat preferredExpandedContentHeight;
@property (nonatomic,readonly) CGFloat preferredExpandedContentWidth;
@property (nonatomic,readonly) BOOL providesOwnPlatter;
@optional
- (BOOL)shouldBeginTransitionToExpandedContentModule;
- (void)willResignActive;
- (void)willBecomeActive;
- (void)willTransitionToExpandedContentMode:(BOOL)arg1;
- (BOOL)shouldFinishTransitionToExpandedContentModule;
- (void)didTransitionToExpandedContentMode:(BOOL)arg1;
- (BOOL)canDismissPresentedContent;
- (void)dismissPresentedContentAnimated:(BOOL)arg1 completion:(/*^block*/ id)arg2;
- (CGFloat)preferredExpandedContentWidth;
- (BOOL)providesOwnPlatter;
- (void)controlCenterWillPresent;
- (void)controlCenterDidDismiss;

@required
- (CGFloat)preferredExpandedContentHeight;

@end
