/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUIKit/ControlCenterUIKit-Structs.h>
#import <UIKit/UIControl.h>
#import <UIKit/UIGestureRecognizer.h>
#import "CCUIContentModuleTopLevelGestureProvider.h"
#import "CCUIContentModuleExpandedStateListener.h"
#import "CCUIContentClipping.h"
#import "CCUIGroupRendering.h"

@class NSArray, CALayer, UIImageView, CCUICAPackageView, NSTimer, UILongPressGestureRecognizer, UISelectionFeedbackGenerator, _UIEdgeFeedbackGenerator, UIImage, CCUICAPackageDescription, NSString;

@interface CCUIModuleSliderView : UIControl <UIGestureRecognizerDelegate, CCUIContentModuleTopLevelGestureProvider, CCUIContentModuleExpandedStateListener, CCUIContentClipping, CCUIGroupRendering> {

	UIImageView* _glyphImageView;
	CCUICAPackageView* _glyphPackageView;
	CCUICAPackageView* _compensatingGlyphPackageView;
	NSArray* _stepBackgroundViews;
	NSArray* _separatorViews;
	CGFloat _startingHeight;
	CGPoint _startingLocation;
	float _startingValue;
	NSTimer* _updatesCommitTimer;
	float _previousValue;
	UILongPressGestureRecognizer* _valueChangeGestureRecognizer;
	UISelectionFeedbackGenerator* _selectionFeedbackGenerator;
	_UIEdgeFeedbackGenerator* _edgeFeedbackGenerator;
	BOOL _glyphVisible;
	BOOL _throttleUpdates;
	BOOL _firstStepIsDisabled;
	BOOL _firstStepIsOff;
	BOOL _interactiveWhenUnexpanded;
	float _value;
	UIImage* _glyphImage;
	CCUICAPackageDescription* _glyphPackageDescription;
	NSString* _glyphState;
	NSUInteger _numberOfSteps;
	NSUInteger _step;

}

@property (assign,getter=isInteractiveWhenUnexpanded,nonatomic) BOOL interactiveWhenUnexpanded;			//@synthesize interactiveWhenUnexpanded=_interactiveWhenUnexpanded - In the implementation block
@property (nonatomic,retain) UIImage * glyphImage;								//@synthesize glyphImage=_glyphImage - In the implementation block
@property (nonatomic,retain) CCUICAPackageDescription * glyphPackageDescription;				//@synthesize glyphPackageDescription=_glyphPackageDescription - In the implementation block
@property (nonatomic,retain) NSString * glyphState;								//@synthesize glyphState=_glyphState - In the implementation block
@property (assign,getter=isGlyphVisible,nonatomic) BOOL glyphVisible;						//@synthesize glyphVisible=_glyphVisible - In the implementation block
@property (assign,nonatomic) BOOL throttleUpdates;								//@synthesize throttleUpdates=_throttleUpdates - In the implementation block
@property (assign,nonatomic) float value;									//@synthesize value=_value - In the implementation block
@property (assign,nonatomic) NSUInteger numberOfSteps;							//@synthesize numberOfSteps=_numberOfSteps - In the implementation block
@property (assign,nonatomic) BOOL firstStepIsDisabled;								//@synthesize firstStepIsDisabled=_firstStepIsDisabled - In the implementation block
@property (assign,nonatomic) BOOL firstStepIsOff;								//@synthesize firstStepIsOff=_firstStepIsOff - In the implementation block
@property (assign,nonatomic) NSUInteger step;								//@synthesize step=_step - In the implementation block
@property (getter=isStepped,nonatomic,readonly) BOOL stepped;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
@property (nonatomic,readonly) NSArray * topLevelGestureRecognizers;
@property (nonatomic,readonly) NSArray * topLevelBlockingGestureRecognizers;
@property (getter=isContentClippingRequired,nonatomic,readonly) BOOL contentClippingRequired;
@property (getter=isGroupRenderingRequired,nonatomic,readonly) BOOL groupRenderingRequired;
@property (nonatomic,readonly) CALayer * punchOutRootLayer;
- (NSUInteger)step;
- (void)setStep:(NSUInteger)arg1;
- (id)initWithFrame:(CGRect)arg1;
- (void)layoutSubviews;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)setValue:(float)arg1;
- (float)value;
- (UIImage *)glyphImage;
- (void)setGlyphImage:(UIImage *)arg1;
- (void)setGlyphPackageDescription:(CCUICAPackageDescription *)arg1;
- (void)setGlyphState:(NSString *)arg1;
- (CCUICAPackageDescription *)glyphPackageDescription;
- (NSString *)glyphState;
- (void)_createStepViewsForNumberOfSteps:(NSUInteger)arg1;
- (void)_handleValueChangeGestureRecognizer:(id)arg1;
- (BOOL)isStepped;
- (NSUInteger)_stepFromValue:(float)arg1;
- (float)_valueFromStep:(NSUInteger)arg1;
- (void)_createSeparatorViewsForNumberOfSteps:(NSUInteger)arg1;
- (id)_newGlyphPackageView;
- (void)_configureGlyphPackageView:(id)arg1;
- (void)_configureCompensatingGlyphPackageView:(id)arg1;
- (void)_layoutValueViews;
- (BOOL)isInteractiveWhenUnexpanded;
- (void)_layoutValueViewsForStepChange:(BOOL)arg1;
- (void)_layoutContinuousValueView;
- (CGFloat)_fullStepHeight;
- (BOOL)firstStepIsOff;
- (CGFloat)_heightForStep:(NSUInteger)arg1;
- (void)_layoutContinuousValueViewForValue:(float)arg1;
- (CGFloat)_sliderHeightForValue:(float)arg1;
- (id)_continuousValueView;
- (id)_createBackgroundViewForStep:(NSUInteger)arg1;
- (id)_createSeparatorView;
- (CGFloat)_sliderHeight;
- (BOOL)firstStepIsDisabled;
- (float)_valueForTouchLocation:(CGPoint)arg1 withAbsoluteReference:(BOOL)arg2;
- (void)_updateStepFromValue:(float)arg1 playHaptic:(BOOL)arg2;
- (void)_layoutValueViewsForStepChange;
- (void)_beginTrackingWithGestureRecognizer:(id)arg1;
- (void)_continueTrackingWithGestureRecognizer:(id)arg1;
- (void)_endTrackingWithGestureRecognizer:(id)arg1;
- (void)_updateValueForTouchLocation:(CGPoint)arg1 withAbsoluteReference:(BOOL)arg2 forContinuedGesture:(BOOL)arg3;
- (void)setFirstStepIsDisabled:(BOOL)arg1;
- (void)setFirstStepIsOff:(BOOL)arg1;
- (BOOL)isGlyphVisible;
- (void)setGlyphVisible:(BOOL)arg1;
- (BOOL)throttleUpdates;
- (void)setThrottleUpdates:(BOOL)arg1;
- (void)setInteractiveWhenUnexpanded:(BOOL)arg1;
- (void)setNumberOfSteps:(NSUInteger)arg1;
- (NSUInteger)numberOfSteps;
- (NSArray *)topLevelBlockingGestureRecognizers;
- (BOOL)isContentClippingRequired;
- (BOOL)isGroupRenderingRequired;
- (CALayer *)punchOutRootLayer;
- (NSArray *)topLevelGestureRecognizers;
- (void)contentModuleWillTransitionToExpandedContentMode:(BOOL)arg1;
@end
