/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUIKit/ControlCenterUIKit-Structs.h>
#import <ControlCenterUIKit/CCUIButtonModuleViewController.h>
#import "CCUIContentModuleContentViewController.h"

@class UILabel, UIView, MTMaterialView, UIStackView, NSMutableArray, UIScrollView, UILongPressGestureRecognizer, UISelectionFeedbackGenerator, CCUIMenuModuleItemView, CCUIContentModuleContext, NSString;

@interface CCUIMenuModuleViewController : CCUIButtonModuleViewController <UIGestureRecognizerDelegate, CCUIContentModuleContentViewController> {

	UILabel* _titleLabel;
	UIView* _headerSeparatorView;
	MTMaterialView* _platterMaterialView;
	UIStackView* _menuItemsContainer;
	NSMutableArray* _menuItemsViews;
	UIScrollView* _contentScrollView;
	UIView* _darkeningBackgroundView;
	UILongPressGestureRecognizer* _pressGestureRecognizer;
	UISelectionFeedbackGenerator* _feedbackGenerator;
	BOOL _ignoreMenuItemAtTouchLocationAfterExpanded;
	CCUIMenuModuleItemView* _menuItemToIgnore;
	BOOL _shouldProvideOwnPlatter;
	BOOL _useTallLayout;
	UIView* _contentView;
	CCUIContentModuleContext* _contentModuleContext;

}

@property (nonatomic) NSMutableArray *menuItems;
@property (assign,nonatomic) NSUInteger indentation;

@property (nonatomic,copy) NSString * title;
@property (nonatomic,readonly) NSUInteger actionsCount;
@property (nonatomic,readonly) CGFloat headerHeight;
@property (nonatomic,readonly) UIView * contentView;							//@synthesize contentView=_contentView - In the implementation block
@property (assign,nonatomic) BOOL shouldProvideOwnPlatter;						//@synthesize shouldProvideOwnPlatter=_shouldProvideOwnPlatter - In the implementation block
@property (assign,nonatomic) BOOL useTallLayout;							//@synthesize useTallLayout=_useTallLayout - In the implementation block
@property (nonatomic,weak) CCUIContentModuleContext * contentModuleContext;		//@synthesize contentModuleContext=_contentModuleContext - In the implementation block
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
@property (nonatomic,readonly) CGFloat preferredExpandedContentHeight;
@property (nonatomic,readonly) CGFloat preferredExpandedContentWidth;
@property (nonatomic,readonly) BOOL providesOwnPlatter;
@property (assign,nonatomic) BOOL useTrailingCheckmarkLayout;
- (NSUInteger)actionsCount;
- (UIView *)contentView;
- (void)dealloc;
- (void)setTitle:(NSString *)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewWillLayoutSubviews;
- (void)_handlePressGesture:(id)arg1;
- (void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidLoad;
- (void)removeAllActions;
- (CGFloat)_separatorHeight;
- (CGFloat)headerHeight;
- (id)_titleFont;
- (void)_contentSizeCategoryDidChange;
- (BOOL)shouldBeginTransitionToExpandedContentModule;
- (void)addActionWithTitle:(id)arg1 subtitle:(id)arg2 glyph:(id)arg3 handler:(/*^block*/ id)arg4;
- (CGFloat)headerHeightForWidth:(CGFloat)arg1;
- (void)_fadeViewsForExpandedState:(BOOL)arg1;
- (void)_setupContentViewBounds;
- (void)_setupMenuItems;
- (void)_layoutViewSubviews;
- (void)_layoutGlyphViewForSize:(CGSize)arg1;
- (void)_layoutTitleLabelForSize:(CGSize)arg1;
- (void)_layoutSeparatorForSize:(CGSize)arg1;
- (CGFloat)preferredExpandedContentHeightWithWidth:(CGFloat)arg1;
- (CGFloat)_maximumHeight;
- (CGFloat)_desiredExpandedHeight;
- (CGFloat)_menuItemsHeightForWidth:(CGFloat)arg1;
- (CGFloat)_contentScaleForSize:(CGSize)arg1;
- (CGAffineTransform)_contentTransformForScale:(CGFloat)arg1;
- (void)setUseTallLayout:(BOOL)arg1;
- (void)_handleActionTapped:(id)arg1;
- (BOOL)shouldProvideOwnPlatter;
- (void)setShouldProvideOwnPlatter:(BOOL)arg1;
- (BOOL)useTallLayout;
- (CGFloat)preferredExpandedContentHeight;
- (void)addActionWithTitle:(id)arg1 glyph:(id)arg2 handler:(/*^block*/ id)arg3;
- (void)willTransitionToExpandedContentMode:(BOOL)arg1;
- (CGFloat)preferredExpandedContentWidth;
- (CCUIContentModuleContext *)contentModuleContext;
- (void)setContentModuleContext:(CCUIContentModuleContext *)arg1;
- (void)_layoutMenuItemsForSize:(CGSize)arg1;
- (void)_setupTitleLabel;
- (void)contentModuleWillTransitionToExpandedContentMode:(BOOL)arg1;
- (void)_updateScrollViewContentSize;
- (void)setFooterButtonTitle:(id)arg1 handler:(/*^block*/id)arg2 ;
- (void)removeFooterButton;
- (void)_updateLeadingAndTrailingViews;
@end
