/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */


@class NSURL;

@interface CCUICAPackageDescription : NSObject {

	BOOL _flipsForRightToLeftLayoutDirection;
	NSURL* _packageURL;

}

@property (nonatomic,copy,readonly) NSURL * packageURL;					//@synthesize packageURL=_packageURL - In the implementation block
@property (assign,nonatomic) BOOL flipsForRightToLeftLayoutDirection;			//@synthesize flipsForRightToLeftLayoutDirection=_flipsForRightToLeftLayoutDirection - In the implementation block
+ (id)descriptionForPackageNamed:(id)arg1 inBundle:(id)arg2;
- (BOOL)flipsForRightToLeftLayoutDirection;
- (id)initWithPackageName:(id)arg1 inBundle:(id)arg2;
- (void)setFlipsForRightToLeftLayoutDirection:(BOOL)arg1;
- (NSURL *)packageURL;
@end
