/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

@class UIViewController;

#import "CCUIContentModuleContentViewController.h"

@protocol CCUIContentModule <NSObject>
@property (nonatomic,readonly) UIViewController<CCUIContentModuleContentViewController>* contentViewController;
@property (nonatomic,readonly) UIViewController * backgroundViewController;
@optional
- (void)setContentModuleContext:(id)arg1;
- (UIViewController *)backgroundViewController;

@required
- (UIViewController<CCUIContentModuleContentViewController>*)contentViewController;

@end
