/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */


@class NSString;

@interface CCUIStatusUpdate : NSObject {

	NSString* _message;
	NSUInteger _type;

}

@property (nonatomic,copy,readonly) NSString * message;			//@synthesize message=_message - In the implementation block
@property (nonatomic,readonly) NSUInteger type;			//@synthesize type=_type - In the implementation block
+ (id)statusUpdateWithMessage:(id)arg1 type:(NSUInteger)arg2;
- (NSUInteger)type;
- (NSString *)message;
- (id)_initWithMessage:(id)arg1 type:(NSUInteger)arg2;
@end
